#!/usr/bin/env node
// project-crew project manager — bootstrap repos, manage git worktrees, checkpoint/resume
// Usage:
//   node project-manager.js --bootstrap <crew.js>    Create repo with .gitignore, LFS, structure
//   node project-manager.js --worktrees <crew.js>    Create parallel worktrees
//   node project-manager.js --checkpoint <crew.js>   Commit current state as checkpoint
//   node project-manager.js --status <crew.js>       Show project status
//   node project-manager.js --rollback <crew.js> --to <commit>  Rollback to commit
//   node project-manager.js --evolve <crew.js>       Compare worktrees, keep best
//   node project-manager.js --merge <crew.js>        Merge best worktree to main

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const args = process.argv.slice(2);
const crewPath = args.find(a => !a.startsWith('--'));

function getCrewDef(p) {
  return require(path.resolve(p));
}

function getProjectRoot(crewDef) {
  return crewDef.workdir || crewDef.repoPath || `/tmp/crew-${crewDef.name}`;
}

function run(cmd, cwd) {
  try {
    return execSync(cmd, { cwd, encoding: 'utf8', timeout: 30000 }).trim();
  } catch (e) {
    return null;
  }
}

// ── .gitignore Templates ──

const GITIGNORE_TEMPLATES = {
  node: `node_modules/
dist/
.env
.env.local
*.log
.DS_Store
coverage/
.nyc_output/
.cache/
.parcel-cache/
.vercel/
.netlify/`,

  python: `__pycache__/
*.py[cod]
*$py.class
*.egg-info/
dist/
build/
.eggs/
*.egg
.env
.venv/
venv/
.ipynb_checkpoints/
.mypy_cache/
.ruff_cache/`,

  rust: `/target/
**/*.rs.bk
Cargo.lock
*.swp
*.swo
*~
.env`,

  go: `/vendor/
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
.env
go.work.sum`,

  general: `.DS_Store
Thumbs.db
*.log
.env
.env.local
tmp/
*.tmp
*.bak
*.swp
*.swo
*~`
};

// ── LFS Patterns ──

const LFS_PATTERNS = {
  'ml-model': ['*.onnx', '*.gguf', '*.safetensors', '*.bin', '*.pt', '*.pth'],
  'media': ['*.png', '*.jpg', '*.jpeg', '*.gif', '*.mp4', '*.mp3', '*.wav', '*.webp'],
  'dataset': ['*.csv', '*.parquet', '*.arrow', '*.feather', '*.jsonl'],
  'binary': ['*.wasm', '*.so', '*.dylib', '*.dll'],
};

// ── Project Bootstrap ──

function bootstrap(crewPath) {
  const crewDef = getCrewDef(crewPath);
  const root = getProjectRoot(crewDef);
  const project = crewDef.project || crewDef.name;

  if (!fs.existsSync(root)) fs.mkdirSync(root, { recursive: true });

  // Init git repo
  if (!fs.existsSync(path.join(root, '.git'))) {
    run('git init', root);
    run('git checkout -b main', root);
  }

  // Detect language from project definition
  const lang = detectLanguage(crewDef);
  const gitignore = GITIGNORE_TEMPLATES[lang] || GITIGNORE_TEMPLATES.general;
  fs.writeFileSync(path.join(root, '.gitignore'), gitignore);

  // LFS setup
  const lfs = crewDef.lfs || [];
  if (lfs.length > 0) {
    run('git lfs install', root);
    for (const pattern of lfs) {
      run(`git lfs track "${pattern}"`, root);
    }
    // Add .gitattributes
    const attrs = lfs.map(p => `${p} filter=lfs diff=lfs merge=lfs -text`).join('\n');
    fs.appendFileSync(path.join(root, '.gitattributes'), attrs + '\n');
  }

  // README
  const readme = `# ${project}

> Generated by project-crew

## Project Goal
${crewDef.goal || 'N/A'}

## Structure
${describeStructure(crewDef)}

## Worktrees
\`\`\`
git worktree list
\`\`\`

## Checkpoints
Each development step creates a git checkpoint. Use:
- \`git log --oneline\` to view checkpoints
- \`git checkout <commit>\` to rollback
\`\`\`
`;
  fs.writeFileSync(path.join(root, 'README.md'), readme);

  // Create directory structure from steps
  createProjectStructure(crewDef, root);

  // Initial commit
  run('git add -A', root);
  run('git commit -m "init: project bootstrap by project-crew"', root) ||
    console.log('(No changes to commit)');

  // Branch: dev
  const devExists = run('git rev-parse --verify dev', root);
  if (!devExists) run('git checkout -b dev', root);
  else run('git checkout dev', root);

  return {
    project,
    root,
    lang,
    lfs: lfs.length > 0,
    gitInitialized: true,
    branch: 'dev',
    structure: describeStructure(crewDef),
  };
}

function detectLanguage(crewDef) {
  const allSteps = crewDef.steps || [];
  for (const step of allSteps) {
    const s = JSON.stringify(step).toLowerCase();
    if (s.includes('node') || s.includes('npm') || s.includes('typescript')) return 'node';
    if (s.includes('python') || s.includes('pip') || s.includes('pytorch')) return 'python';
    if (s.includes('rust') || s.includes('cargo')) return 'rust';
    if (s.includes('go') || s.includes('golang')) return 'go';
  }
  // Check project.lang hint
  if (crewDef.project?.lang) return crewDef.project.lang;
  return 'general';
}

function describeStructure(crewDef) {
  const lines = [];
  for (const step of (crewDef.steps || [])) {
    const outputs = step.output ? (Array.isArray(step.output) ? step.output : [step.output]) : [];
    for (const f of outputs) {
      const dir = path.dirname(f);
      if (dir && dir !== '.') lines.push(`- \`${dir}/\` — ${step.id} output`);
    }
  }
  return lines.join('\n') || '- (flat structure, all files in root)';
}

function createProjectStructure(crewDef, root) {
  for (const step of (crewDef.steps || [])) {
    const outputs = step.output ? (Array.isArray(step.output) ? step.output : [step.output]) : [];
    for (const f of outputs) {
      const dir = path.dirname(f);
      if (dir && dir !== '.' && !fs.existsSync(path.join(root, dir))) {
        fs.mkdirSync(path.join(root, dir), { recursive: true });
      }
    }
  }
}

// ── Git Worktree Parallel Development ──

function createWorktrees(crewPath) {
  const crewDef = getCrewDef(crewPath);
  const root = getProjectRoot(crewDef);
  const count = crewDef.worktrees || 2;
  const strategy = crewDef.evolveStrategy || 'best-output';

  // Ensure we're on main and it has at least one commit
  run('git checkout main', root);

  const worktrees = [];
  for (let i = 0; i < count; i++) {
    const branchName = `wt-${String(i + 1).padStart(2, '0')}`;
    const wtPath = path.resolve(root, `../${crewDef.name}-wt${i + 1}`);

    // Clean up if exists
    if (fs.existsSync(wtPath)) fs.rmSync(wtPath, { recursive: true });

    // Create branch from current HEAD
    run(`git branch ${branchName} 2>/dev/null || true`, root);

    // Create worktree
    const wtResult = run(`git worktree add "${wtPath}" "${branchName}" 2>&1`, root);
    if (!wtResult || wtResult.includes('fatal')) {
      // Branch might already exist, try force
      run(`git worktree add -f "${wtPath}" "${branchName}" 2>&1`, root);
    }

    // Copy crew.js to worktree
    fs.mkdirSync(wtPath, { recursive: true });
    fs.copyFileSync(path.resolve(crewPath), path.join(wtPath, 'crew.js'));

    worktrees.push({
      id: i + 1,
      branch: branchName,
      path: wtPath,
      status: 'ready',
    });
  }

  // Save worktree metadata
  const meta = {
    project: crewDef.name,
    count,
    strategy,
    worktrees,
    createdAt: new Date().toISOString(),
  };
  fs.writeFileSync(path.join(root, '.crew-meta.json'), JSON.stringify(meta, null, 2));

  return {
    count,
    strategy,
    worktrees,
    instruction: `Parallel development initialized. Each worktree has its own branch. Execute the crew DAG independently in each worktree, then run --evolve to compare.`,
  };
}

// ── Checkpoint ──

function checkpoint(crewPath) {
  const crewDef = getCrewDef(crewPath);
  const root = getProjectRoot(crewDef);
  const stepId = args[args.indexOf('--step') + 1] || 'manual';
  const msg = args[args.indexOf('--message') + 1] || `checkpoint: ${stepId} completed`;

  run('git add -A', root);
  const hash = run(`git commit -m "${msg}"`, root);

  return {
    step: stepId,
    commit: hash,
    message: msg,
    timestamp: new Date().toISOString(),
  };
}

// ── Status ──

function status(crewPath) {
  const crewDef = getCrewDef(crewPath);
  const root = getProjectRoot(crewDef);

  const currentBranch = run('git branch --show-current', root) || 'unknown';
  const log = run('git log --oneline -20', root) || '(no commits)';
  const worktrees = run('git worktree list', root) || '(no worktrees)';

  let meta = null;
  const metaPath = path.join(root, '.crew-meta.json');
  if (fs.existsSync(metaPath)) {
    meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
  }

  return {
    project: crewDef.name,
    root,
    branch: currentBranch,
    recentCheckpoints: log.split('\n').filter(Boolean),
    worktrees: worktrees.split('\n').filter(Boolean),
    parallelConfig: meta,
  };
}

// ── Rollback ──

function rollback(crewPath) {
  const crewDef = getCrewDef(crewPath);
  const root = getProjectRoot(crewDef);
  const targetCommit = args[args.indexOf('--to') + 1];

  if (!targetCommit) {
    return { error: 'Missing --to <commit>. Use --status to see available checkpoints.' };
  }

  // Check if commit exists
  const valid = run(`git cat-file -t ${targetCommit}`, root);
  if (!valid) {
    return { error: `Commit ${targetCommit} not found` };
  }

  // Create recovery branch before rollback
  const recoveryBranch = `recovery-${Date.now()}`;
  run(`git branch ${recoveryBranch}`, root);

  // Reset to target
  run(`git reset --hard ${targetCommit}`, root);

  return {
    rollbackTo: targetCommit,
    recoveryBranch,
    message: `Rolled back to ${targetCommit}. Recovery branch: ${recoveryBranch}`,
    instruction: `To resume from this point, execute the crew DAG starting from the current state.`,
  };
}

// ── Evolve (Compare & Select Best) ──

function evolve(crewPath) {
  const crewDef = getCrewDef(crewPath);
  const root = getProjectRoot(crewDef);
  const metaPath = path.join(root, '.crew-meta.json');

  if (!fs.existsSync(metaPath)) {
    return { error: 'No parallel worktree config found. Run --worktrees first.' };
  }

  const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
  const results = [];

  for (const wt of meta.worktrees) {
    const wtPath = wt.path;
    if (!fs.existsSync(wtPath)) {
      results.push({ id: wt.id, branch: wt.branch, status: 'missing' });
      continue;
    }

    // Evaluate worktree: count commits, check output files
    const commitCount = (run('git log --oneline', wtPath) || '').split('\n').filter(Boolean).length;
    const lastCommit = run('git log --oneline -1', wtPath) || '(none)';
    const outputFiles = evaluateOutputs(crewDef, wtPath);
    const score = outputFiles.totalScore;

    results.push({
      id: wt.id,
      branch: wt.branch,
      path: wtPath,
      commits: commitCount,
      lastCommit,
      outputs: outputFiles,
      score,
    });
  }

  // Rank by score
  results.sort((a, b) => (b.score || 0) - (a.score || 0));

  // Mark survivors and pruned
  const survivors = [];
  const pruned = [];
  for (let i = 0; i < results.length; i++) {
    if (i === 0 || (results[i].score || 0) >= (results[0].score || 0) * 0.8) {
      results[i].decision = 'survive';
      survivors.push(results[i]);
    } else {
      results[i].decision = 'prune';
      pruned.push(results[i]);
    }
  }

  return {
    strategy: meta.strategy,
    results,
    best: results[0],
    survivors,
    pruned,
    instruction: pruned.length > 0
      ? `Best worktree: ${results[0].branch} (score: ${results[0].score}). Pruned ${pruned.length} underperformer(s). To merge best: run --merge`
      : `All worktrees performing well. Best: ${results[0].branch}`,
  };
}

function evaluateOutputs(crewDef, wtPath) {
  const checks = [];
  let totalScore = 0;
  let maxScore = 0;

  for (const step of (crewDef.steps || [])) {
    const outputs = step.output ? (Array.isArray(step.output) ? step.output : [step.output]) : [];
    for (const f of outputs) {
      maxScore += 10;
      const filePath = path.join(wtPath, f);
      if (!fs.existsSync(filePath)) {
        checks.push({ file: f, exists: false, score: 0 });
        continue;
      }
      const stat = fs.statSync(filePath);
      const size = stat.size;
      let score = 5; // exists = 5 points
      if (size > 100) score = 7;
      if (size > 500) score = 8;
      if (size > 2000) score = 9;
      if (size > 5000) score = 10;
      totalScore += score;
      checks.push({ file: f, exists: true, size, score });
    }
  }

  return { checks, totalScore, maxScore };
}

// ── Merge Best ──

function mergeBest(crewPath) {
  const crewDef = getCrewDef(crewPath);
  const root = getProjectRoot(crewDef);
  const metaPath = path.join(root, '.crew-meta.json');

  if (!fs.existsSync(metaPath)) {
    return { error: 'No parallel worktree config found.' };
  }

  // Run evolve to find best
  const evolveResult = evolve(crewPath);
  if (!evolveResult.best) {
    return { error: 'No worktrees to merge.' };
  }

  const best = evolveResult.best;
  run('git checkout main', root);

  // Merge best branch into main
  const mergeResult = run(`git merge ${best.branch} --no-edit`, root);

  return {
    mergedFrom: best.branch,
    score: best.score,
    mergeResult: mergeResult || 'already up to date',
    message: `Merged best worktree (${best.branch}) into main.`,
  };
}

// ── CLI ──

const command = args.find(a => a.startsWith('--'))?.replace('--', '');

if (!crewPath || !command) {
  console.error(`Usage: node project-manager.js --<command> <crew.js>
Commands:
  --bootstrap    Create repo with .gitignore, LFS, directory structure
  --worktrees    Create N parallel git worktrees (N = crew.worktrees or 2)
  --checkpoint   Commit current state (--step <id> --message <msg>)
  --status       Show project status, checkpoints, worktrees
  --rollback     Rollback to a commit (--to <commit>)
  --evolve       Compare worktrees, keep best, prune underperformers
  --merge        Merge best worktree into main`);
  process.exit(1);
}

try {
  let result;
  switch (command) {
    case 'bootstrap': result = bootstrap(crewPath); break;
    case 'worktrees': result = createWorktrees(crewPath); break;
    case 'checkpoint': result = checkpoint(crewPath); break;
    case 'status': result = status(crewPath); break;
    case 'rollback': result = rollback(crewPath); break;
    case 'evolve': result = evolve(crewPath); break;
    case 'merge': result = mergeBest(crewPath); break;
    default: console.error(`Unknown command: --${command}`); process.exit(1);
  }
  console.log(JSON.stringify(result, null, 2));
} catch (e) {
  console.error(`Error: ${e.message}`);
  process.exit(1);
}
